
import { 
    IPO, Subproject, Training, OtherActivity, OfficeRequirement, 
    StaffingRequirement, OtherProgramExpense, initialUacsCodes, 
    initialParticularTypes, ReferenceUacs, ReferenceParticular 
} from './constants';

// --- Helper Functions for Reference Lists ---
const flattenUacs = () => {
    const list: any[] = [];
    let id = 1;
    for (const objType in initialUacsCodes) {
        for (const particular in initialUacsCodes[objType]) {
             for (const code in initialUacsCodes[objType][particular]) {
                 list.push({
                     id: String(id++),
                     objectType: objType,
                     particular: particular,
                     uacsCode: code,
                     description: initialUacsCodes[objType][particular][code]
                 });
             }
        }
    }
    return list;
};

const flattenParticulars = () => {
    const list: any[] = [];
    let id = 1;
    for (const type in initialParticularTypes) {
        initialParticularTypes[type].forEach(p => {
            list.push({
                id: String(id++),
                type: type,
                particular: p
            });
        });
    }
    return list;
}

export const sampleReferenceUacsList: ReferenceUacs[] = flattenUacs();
export const sampleReferenceParticularList: ReferenceParticular[] = flattenParticulars();

// --- Sample Data: IPOs (10 Entries) ---
export const sampleIPOs: IPO[] = [
    {
        id: 1,
        name: "Samahan ng mga Katutubong Dumagat",
        acronym: "SKD",
        location: "Brgy. Daraitan, Tanay, Rizal",
        region: "Region IV-A (CALABARZON)",
        indigenousCulturalCommunity: "Dumagat",
        ancestralDomainNo: "R4A-RIZ-TAN-001",
        registeringBody: "SEC",
        isWomenLed: false,
        isWithinGida: true,
        isWithinElcac: false,
        isWithScad: true,
        contactPerson: "Juan dela Cruz",
        contactNumber: "09171234567",
        registrationDate: "2020-05-15",
        commodities: [{ type: "Crop Commodity", particular: "Coffee Seedlings", value: 50, isScad: true }],
        levelOfDevelopment: 3,
        lat: 14.6127,
        lng: 121.3632,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 2,
        name: "Dumagat-Remontado of General Nakar",
        acronym: "DRGN",
        location: "General Nakar, Quezon",
        region: "Region IV-A (CALABARZON)",
        indigenousCulturalCommunity: "Dumagat-Remontado",
        ancestralDomainNo: "R4A-QUE-GEN-010",
        registeringBody: "NCIP",
        isWomenLed: true,
        isWithinGida: true,
        isWithinElcac: true,
        isWithScad: true,
        contactPerson: "Kakay Tolits",
        contactNumber: "09151112222",
        registrationDate: "2018-05-25",
        commodities: [{ type: "Crop Commodity", particular: "Coconut", value: 200, isScad: true }],
        levelOfDevelopment: 3,
        lat: 14.7648,
        lng: 121.6366,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 3,
        name: "Higaonon Tribal Farmers Association",
        acronym: "HTFA",
        location: "Malaybalay City, Bukidnon",
        region: "Region X (Northern Mindanao)",
        indigenousCulturalCommunity: "Higaonon",
        ancestralDomainNo: "R10-BUK-MAL-003",
        registeringBody: "DOLE",
        isWomenLed: false,
        isWithinGida: true,
        isWithinElcac: false,
        isWithScad: true,
        contactPerson: "Datu Mantukay",
        contactNumber: "09181234567",
        registrationDate: "2019-02-10",
        commodities: [{ type: "Crop Commodity", particular: "Abaca Corms", value: 15, isScad: true }],
        levelOfDevelopment: 2,
        lat: 8.1574,
        lng: 125.1277,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 4,
        name: "Manobo Cultural Community Inc.",
        acronym: "MCCI",
        location: "Prosperidad, Agusan del Sur",
        region: "Region XIII (Caraga)",
        indigenousCulturalCommunity: "Manobo",
        ancestralDomainNo: "R13-AGS-PRO-004",
        registeringBody: "SEC",
        isWomenLed: true,
        isWithinGida: true,
        isWithinElcac: true,
        isWithScad: false,
        contactPerson: "Bae Aida",
        contactNumber: "09201234567",
        registrationDate: "2021-08-15",
        commodities: [{ type: "Crop Commodity", particular: "Cacao", value: 10, isScad: false }],
        levelOfDevelopment: 2,
        lat: 8.5990,
        lng: 125.9220,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 5,
        name: "Tboli Weavers Association",
        acronym: "TWA",
        location: "Lake Sebu, South Cotabato",
        region: "Region XII (SOCCSKSARGEN)",
        indigenousCulturalCommunity: "Tboli",
        ancestralDomainNo: "R12-SOC-LAK-005",
        registeringBody: "CDA",
        isWomenLed: true,
        isWithinGida: false,
        isWithinElcac: false,
        isWithScad: true,
        contactPerson: "Ye Lang Dulay",
        contactNumber: "09191234567",
        registrationDate: "2017-11-20",
        commodities: [{ type: "Equipment", particular: "Weaving Loom", value: 20, isScad: true }],
        levelOfDevelopment: 4,
        lat: 6.2239,
        lng: 124.7032,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 6,
        name: "Igorot Organic Farmers",
        acronym: "IOF",
        location: "La Trinidad, Benguet",
        region: "Cordillera Administrative Region (CAR)",
        indigenousCulturalCommunity: "Igorot",
        ancestralDomainNo: "CAR-BEN-LAT-006",
        registeringBody: "DOLE",
        isWomenLed: false,
        isWithinGida: false,
        isWithinElcac: false,
        isWithScad: true,
        contactPerson: "Manong Ben",
        contactNumber: "09179998888",
        registrationDate: "2016-03-12",
        commodities: [{ type: "Crop Commodity", particular: "Vegetable Seeds", value: 100, isScad: true }],
        levelOfDevelopment: 5,
        lat: 16.4568,
        lng: 120.5896,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 7,
        name: "Aeta Magbukun Tribe",
        acronym: "AMT",
        location: "Abucay, Bataan",
        region: "Region III (Central Luzon)",
        indigenousCulturalCommunity: "Aeta",
        ancestralDomainNo: "R3-BAT-ABU-007",
        registeringBody: "NCIP",
        isWomenLed: false,
        isWithinGida: true,
        isWithinElcac: true,
        isWithScad: false,
        contactPerson: "Kapitan Tubig",
        contactNumber: "09165554444",
        registrationDate: "2022-01-10",
        commodities: [{ type: "Crop Commodity", particular: "Sweet Potato", value: 5, isScad: false }],
        levelOfDevelopment: 1,
        lat: 14.7196,
        lng: 120.5042,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 8,
        name: "Mangyan Hanunuo Heritage",
        acronym: "MHH",
        location: "Mansalay, Oriental Mindoro",
        region: "MIMAROPA Region",
        indigenousCulturalCommunity: "Mangyan",
        ancestralDomainNo: "R4B-ORM-MAN-008",
        registeringBody: "SEC",
        isWomenLed: true,
        isWithinGida: true,
        isWithinElcac: false,
        isWithScad: true,
        contactPerson: "Nanay Lita",
        contactNumber: "09187776666",
        registrationDate: "2019-09-09",
        commodities: [{ type: "Crop Commodity", particular: "Banana", value: 50, isScad: true }],
        levelOfDevelopment: 2,
        lat: 12.5463,
        lng: 121.4392,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 9,
        name: "Subanen River Dwellers",
        acronym: "SRD",
        location: "Lakewood, Zamboanga del Sur",
        region: "Region IX (Zamboanga Peninsula)",
        indigenousCulturalCommunity: "Subanen",
        ancestralDomainNo: "R9-ZDS-LAK-009",
        registeringBody: "CDA",
        isWomenLed: false,
        isWithinGida: true,
        isWithinElcac: true,
        isWithScad: true,
        contactPerson: "Timuay Jose",
        contactNumber: "09213332222",
        registrationDate: "2020-12-01",
        commodities: [{ type: "Livestock", particular: "Chicken", value: 500, isScad: true }],
        levelOfDevelopment: 3,
        lat: 7.8467,
        lng: 123.1585,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 10,
        name: "Ati Community of Boracay",
        acronym: "ACB",
        location: "Malay, Aklan",
        region: "Region VI (Western Visayas)",
        indigenousCulturalCommunity: "Ati",
        ancestralDomainNo: "R6-AKL-MAL-010",
        registeringBody: "NCIP",
        isWomenLed: true,
        isWithinGida: false,
        isWithinElcac: false,
        isWithScad: true,
        contactPerson: "Sister Delsa",
        contactNumber: "09171110000",
        registrationDate: "2015-06-15",
        commodities: [{ type: "Other", particular: "Handicrafts", value: 100, isScad: true }],
        levelOfDevelopment: 4,
        lat: 11.9674,
        lng: 121.9248,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
];

// --- Sample Data: Subprojects (10 Entries) ---
export const sampleSubprojects: Subproject[] = [
    {
        id: 1,
        uid: "SP-2024-001",
        name: "Coffee Production and Processing Project",
        location: "Brgy. Daraitan, Tanay, Rizal",
        indigenousPeopleOrganization: "Samahan ng mga Katutubong Dumagat",
        ipo_id: 1,
        status: "Ongoing",
        details: [
            { id: 1, type: "Crop Commodity", particulars: "Coffee Seedlings", deliveryDate: "2024-02-15", unitOfMeasure: "pcs", pricePerUnit: 50, numberOfUnits: 1000, objectType: "MOOE", expenseParticular: "Agricultural and Marine Supplies Expenses", uacsCode: "50203080-00", obligationMonth: "2024-01-30", disbursementMonth: "2024-02-28", actualDeliveryDate: "2024-02-20", actualObligationDate: "2024-02-01", actualDisbursementDate: "2024-03-01", actualAmount: 50000 },
            { id: 2, type: "Equipment", particulars: "Coffee Roaster", deliveryDate: "2024-06-30", unitOfMeasure: "unit", pricePerUnit: 150000, numberOfUnits: 1, objectType: "CO", expenseParticular: "Machinery and Equipment", uacsCode: "10605030-00", obligationMonth: "2024-03-15", disbursementMonth: "2024-07-15" }
        ],
        subprojectCommodities: [{ typeName: "Crop Commodity", name: "Coffee", area: 2, averageYield: 500 }],
        packageType: "Package 1",
        startDate: "2024-01-15",
        estimatedCompletionDate: "2024-12-15",
        lat: 14.6127,
        lng: 121.3632,
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO 4A",
        encodedBy: "Juan Dela Cruz",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 2,
        uid: "SP-2024-002",
        name: "Abaca Fiber Production Expansion",
        location: "Malaybalay City, Bukidnon",
        indigenousPeopleOrganization: "Higaonon Tribal Farmers Association",
        ipo_id: 3,
        status: "Completed",
        details: [
            { id: 3, type: "Crop Commodity", particulars: "Abaca Corms", deliveryDate: "2024-01-20", unitOfMeasure: "pcs", pricePerUnit: 30, numberOfUnits: 5000, objectType: "MOOE", expenseParticular: "Agricultural and Marine Supplies Expenses", uacsCode: "50203080-00", obligationMonth: "2024-01-10", disbursementMonth: "2024-01-25", actualDeliveryDate: "2024-01-20", actualObligationDate: "2024-01-10", actualDisbursementDate: "2024-01-25", actualAmount: 150000 },
            { id: 4, type: "Equipment", particulars: "Stripping Machine", deliveryDate: "2024-03-01", unitOfMeasure: "unit", pricePerUnit: 80000, numberOfUnits: 2, objectType: "CO", expenseParticular: "Machinery and Equipment", uacsCode: "10605030-00", obligationMonth: "2024-02-01", disbursementMonth: "2024-03-15", actualDeliveryDate: "2024-03-05", actualObligationDate: "2024-02-05", actualDisbursementDate: "2024-03-20", actualAmount: 160000 }
        ],
        subprojectCommodities: [{ typeName: "Crop Commodity", name: "Abaca", area: 5, averageYield: 800, actualYield: 850 }],
        packageType: "Package 2",
        startDate: "2024-01-05",
        estimatedCompletionDate: "2024-04-30",
        actualCompletionDate: "2024-03-05",
        lat: 8.1574,
        lng: 125.1277,
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO 10",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 3,
        uid: "SP-2024-003",
        name: "Cacao Nursery Establishment",
        location: "Prosperidad, Agusan del Sur",
        indigenousPeopleOrganization: "Manobo Cultural Community Inc.",
        ipo_id: 4,
        status: "Ongoing",
        details: [
            { id: 5, type: "Construction Materials", particulars: "Net Mesh", deliveryDate: "2024-05-15", unitOfMeasure: "rolls", pricePerUnit: 2500, numberOfUnits: 20, objectType: "MOOE", expenseParticular: "Other Supplies and Materials Expenses", uacsCode: "50203990-00", obligationMonth: "2024-04-30", disbursementMonth: "2024-05-20" }
        ],
        subprojectCommodities: [{ typeName: "Crop Commodity", name: "Cacao", area: 1, averageYield: 0 }],
        packageType: "Package 3",
        startDate: "2024-04-01",
        estimatedCompletionDate: "2024-09-30",
        lat: 8.5990,
        lng: 125.9220,
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 2",
        operatingUnit: "RPMO 13",
        encodedBy: "Bae Aida",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 4,
        uid: "SP-2024-004",
        name: "Native Chicken Dispersal",
        location: "Lakewood, Zamboanga del Sur",
        indigenousPeopleOrganization: "Subanen River Dwellers",
        ipo_id: 9,
        status: "Proposed",
        details: [
            { id: 6, type: "Livestock", particulars: "Native Chicken Pullets", deliveryDate: "2024-08-15", unitOfMeasure: "heads", pricePerUnit: 350, numberOfUnits: 500, objectType: "CO", expenseParticular: "Breeding Stocks", uacsCode: "10607010-00", obligationMonth: "2024-07-15", disbursementMonth: "2024-08-30" }
        ],
        subprojectCommodities: [{ typeName: "Livestock", name: "Poultry", area: 500 }],
        packageType: "Package 1",
        startDate: "2024-07-01",
        estimatedCompletionDate: "2024-10-30",
        lat: 7.8467,
        lng: 123.1585,
        fundingYear: 2024,
        fundType: "Insertion",
        tier: "Tier 1",
        operatingUnit: "RPMO 9",
        encodedBy: "Timuay Jose",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 5,
        uid: "SP-2024-005",
        name: "Vegetable Production Support",
        location: "La Trinidad, Benguet",
        indigenousPeopleOrganization: "Igorot Organic Farmers",
        ipo_id: 6,
        status: "Ongoing",
        details: [
            { id: 7, type: "Crop Commodity", particulars: "Assorted Vegetable Seeds", deliveryDate: "2024-02-15", unitOfMeasure: "packs", pricePerUnit: 150, numberOfUnits: 200, objectType: "MOOE", expenseParticular: "Agricultural and Marine Supplies Expenses", uacsCode: "50203080-00", obligationMonth: "2024-01-30", disbursementMonth: "2024-02-28", actualDeliveryDate: "2024-02-10", actualAmount: 30000, actualObligationDate: "2024-02-01", actualDisbursementDate: "2024-02-25" },
            { id: 8, type: "Crop Commodity", particulars: "Organic Fertilizer", deliveryDate: "2024-02-15", unitOfMeasure: "bags", pricePerUnit: 800, numberOfUnits: 100, objectType: "MOOE", expenseParticular: "Agricultural and Marine Supplies Expenses", uacsCode: "50203080-00", obligationMonth: "2024-01-30", disbursementMonth: "2024-02-28" }
        ],
        subprojectCommodities: [{ typeName: "Crop Commodity", name: "Vegetables", area: 3, averageYield: 2000 }],
        packageType: "Package 2",
        startDate: "2024-01-15",
        estimatedCompletionDate: "2024-06-30",
        lat: 16.4568,
        lng: 120.5896,
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO CAR",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 6,
        uid: "SP-2024-006",
        name: "Weaving Center Enhancement",
        location: "Lake Sebu, South Cotabato",
        indigenousPeopleOrganization: "Tboli Weavers Association",
        ipo_id: 5,
        status: "Ongoing",
        details: [
            { id: 9, type: "Equipment", particulars: "High-Speed Sewing Machine", deliveryDate: "2024-05-30", unitOfMeasure: "unit", pricePerUnit: 25000, numberOfUnits: 5, objectType: "CO", expenseParticular: "Machinery and Equipment", uacsCode: "10605030-00", obligationMonth: "2024-04-15", disbursementMonth: "2024-06-15" }
        ],
        packageType: "Package 4",
        startDate: "2024-03-01",
        estimatedCompletionDate: "2024-08-30",
        lat: 6.2239,
        lng: 124.7032,
        fundingYear: 2024,
        fundType: "Continuing",
        tier: "Tier 1",
        operatingUnit: "RPMO 12",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 7,
        uid: "SP-2024-007",
        name: "Sweet Potato Processing",
        location: "Abucay, Bataan",
        indigenousPeopleOrganization: "Aeta Magbukun Tribe",
        ipo_id: 7,
        status: "Proposed",
        details: [
            { id: 10, type: "Equipment", particulars: "Heavy Duty Mixer", deliveryDate: "2024-09-30", unitOfMeasure: "unit", pricePerUnit: 40000, numberOfUnits: 1, objectType: "CO", expenseParticular: "Machinery and Equipment", uacsCode: "10605030-00", obligationMonth: "2024-08-15", disbursementMonth: "2024-10-15" }
        ],
        subprojectCommodities: [{ typeName: "Crop Commodity", name: "Root Crops", area: 0, averageYield: 0 }],
        packageType: "Package 3",
        startDate: "2024-08-01",
        estimatedCompletionDate: "2024-12-15",
        lat: 14.7196,
        lng: 120.5042,
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 2",
        operatingUnit: "RPMO 3",
        encodedBy: "Kapitan Tubig",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 8,
        uid: "SP-2024-008",
        name: "Banana Plantation Rehabilitation",
        location: "Mansalay, Oriental Mindoro",
        indigenousPeopleOrganization: "Mangyan Hanunuo Heritage",
        ipo_id: 8,
        status: "Cancelled",
        details: [
            { id: 11, type: "Crop Commodity", particulars: "Banana Suckers", deliveryDate: "2024-02-28", unitOfMeasure: "pcs", pricePerUnit: 25, numberOfUnits: 2000, objectType: "MOOE", expenseParticular: "Agricultural and Marine Supplies Expenses", uacsCode: "50203080-00", obligationMonth: "2024-01-30", disbursementMonth: "2024-03-15" }
        ],
        subprojectCommodities: [{ typeName: "Crop Commodity", name: "Banana", area: 4, averageYield: 0 }],
        packageType: "Package 1",
        startDate: "2024-01-15",
        estimatedCompletionDate: "2024-07-30",
        lat: 12.5463,
        lng: 121.4392,
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO 4B",
        encodedBy: "Admin User",
        remarks: "Cancelled due to land dispute issues.",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 9,
        uid: "SP-2024-009",
        name: "Handicraft Souvenir Shop Construction",
        location: "Malay, Aklan",
        indigenousPeopleOrganization: "Ati Community of Boracay",
        ipo_id: 10,
        status: "Completed",
        details: [
            { id: 13, type: "Infrastructure", particulars: "Souvenir Shop Building", deliveryDate: "2023-11-30", unitOfMeasure: "lot", pricePerUnit: 1200000, numberOfUnits: 1, objectType: "CO", expenseParticular: "Buildings and Other Structures", uacsCode: "10604020-00", obligationMonth: "2023-06-15", disbursementMonth: "2023-12-15", actualDeliveryDate: "2023-11-25", actualObligationDate: "2023-06-10", actualDisbursementDate: "2023-12-10", actualAmount: 1200000 }
        ],
        packageType: "Package 5",
        startDate: "2023-06-01",
        estimatedCompletionDate: "2023-12-15",
        actualCompletionDate: "2023-11-25",
        lat: 11.9674,
        lng: 121.9248,
        fundingYear: 2023,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO 6",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 10,
        uid: "SP-2024-010",
        name: "Coconut Processing Facility",
        location: "General Nakar, Quezon",
        indigenousPeopleOrganization: "Dumagat-Remontado of General Nakar",
        ipo_id: 2,
        status: "Proposed",
        details: [
            { id: 12, type: "Infrastructure", particulars: "Processing Shed", deliveryDate: "2024-07-30", unitOfMeasure: "lot", pricePerUnit: 500000, numberOfUnits: 1, objectType: "CO", expenseParticular: "Buildings and Other Structures", uacsCode: "10604020-00", obligationMonth: "2024-05-15", disbursementMonth: "2024-08-15" }
        ],
        subprojectCommodities: [{ typeName: "Crop Commodity", name: "Coconut", area: 0, averageYield: 0 }],
        packageType: "Package 4",
        startDate: "2024-06-01",
        estimatedCompletionDate: "2024-12-30",
        lat: 14.7648,
        lng: 121.6366,
        fundingYear: 2024,
        fundType: "Insertion",
        tier: "Tier 1",
        operatingUnit: "RPMO 4A",
        encodedBy: "Kakay Tolits",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
];

// --- Sample Data: Trainings (10 Entries) ---
export const sampleTrainings: Training[] = [
    {
        id: 1,
        uid: "TRN-2024-001",
        name: "Social Preparation Training",
        date: "2024-01-20",
        description: "Community organizing and leadership basics for IPO members.",
        location: "Brgy. Daraitan, Tanay, Rizal",
        facilitator: "Mr. Juan Tamad",
        participatingIpos: ["Samahan ng mga Katutubong Dumagat"],
        participating_ipo_ids: [1],
        lat: 14.6127,
        lng: 121.3632,
        participantsMale: 15,
        participantsFemale: 20,
        expenses: [
            { id: 1, objectType: "MOOE", expenseParticular: "Training Expenses", uacsCode: "50202010-01", obligationMonth: "2024-01-10", disbursementMonth: "2024-01-25", amount: 35000, actualAmount: 34500, actualObligationDate: "2024-01-12", actualDisbursementDate: "2024-01-28" }
        ],
        component: "Social Preparation",
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO 4A",
        encodedBy: "Admin User",
        actualDate: "2024-01-20",
        actualParticipantsMale: 15,
        actualParticipantsFemale: 20,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 2,
        uid: "TRN-2024-002",
        name: "Abaca Fiber Quality Management",
        date: "2024-02-15",
        description: "Training on stripping and grading abaca fiber.",
        location: "Malaybalay City, Bukidnon",
        facilitator: "PhilFIDA Representative",
        participatingIpos: ["Higaonon Tribal Farmers Association"],
        participating_ipo_ids: [3],
        lat: 8.1574,
        lng: 125.1277,
        participantsMale: 25,
        participantsFemale: 5,
        expenses: [
            { id: 2, objectType: "MOOE", expenseParticular: "Training Expenses", uacsCode: "50202010-01", obligationMonth: "2024-02-01", disbursementMonth: "2024-02-20", amount: 45000 }
        ],
        component: "Production and Livelihood",
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO 10",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 3,
        uid: "TRN-2024-003",
        name: "Cacao Fermentation Techniques",
        date: "2024-06-10",
        description: "Post-harvest processing for cacao.",
        location: "Prosperidad, Agusan del Sur",
        facilitator: "DA-HVCDP Specialist",
        participatingIpos: ["Manobo Cultural Community Inc."],
        participating_ipo_ids: [4],
        lat: 8.5990,
        lng: 125.9220,
        participantsMale: 10,
        participantsFemale: 10,
        expenses: [
            { id: 3, objectType: "MOOE", expenseParticular: "Training Expenses", uacsCode: "50202010-01", obligationMonth: "2024-05-15", disbursementMonth: "2024-06-15", amount: 30000 }
        ],
        component: "Production and Livelihood",
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 2",
        operatingUnit: "RPMO 13",
        encodedBy: "Bae Aida",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 4,
        uid: "TRN-2024-004",
        name: "Financial Literacy Workshop",
        date: "2024-03-05",
        description: "Basic bookkeeping and financial management.",
        location: "General Nakar, Quezon",
        facilitator: "Local Accountant",
        participatingIpos: ["Dumagat-Remontado of General Nakar"],
        participating_ipo_ids: [2],
        lat: 14.7648,
        lng: 121.6366,
        participantsMale: 5,
        participantsFemale: 15,
        expenses: [
            { id: 4, objectType: "MOOE", expenseParticular: "Training Expenses", uacsCode: "50202010-01", obligationMonth: "2024-02-20", disbursementMonth: "2024-03-10", amount: 20000 }
        ],
        component: "Social Preparation",
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO 4A",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 5,
        uid: "TRN-2024-005",
        name: "Weaving Design and Marketing",
        date: "2024-07-20",
        description: "Modernizing weaving designs and market trends.",
        location: "Lake Sebu, South Cotabato",
        facilitator: "DTI Designer",
        participatingIpos: ["Tboli Weavers Association"],
        participating_ipo_ids: [5],
        lat: 6.2239,
        lng: 124.7032,
        participantsMale: 2,
        participantsFemale: 28,
        expenses: [
            { id: 5, objectType: "MOOE", expenseParticular: "Training Expenses", uacsCode: "50202010-01", obligationMonth: "2024-07-01", disbursementMonth: "2024-07-25", amount: 50000 }
        ],
        component: "Marketing and Enterprise",
        fundingYear: 2024,
        fundType: "Continuing",
        tier: "Tier 1",
        operatingUnit: "RPMO 12",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 6,
        uid: "TRN-2024-006",
        name: "Organic Vegetable Farming",
        date: "2024-04-10",
        description: "Principles of organic agriculture.",
        location: "La Trinidad, Benguet",
        facilitator: "ATI CAR",
        participatingIpos: ["Igorot Organic Farmers"],
        participating_ipo_ids: [6],
        lat: 16.4568,
        lng: 120.5896,
        participantsMale: 20,
        participantsFemale: 20,
        expenses: [
            { id: 6, objectType: "MOOE", expenseParticular: "Training Expenses", uacsCode: "50202010-01", obligationMonth: "2024-03-25", disbursementMonth: "2024-04-15", amount: 40000 }
        ],
        component: "Production and Livelihood",
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO CAR",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 7,
        uid: "TRN-2024-007",
        name: "Poultry Management",
        date: "2024-08-05",
        description: "Health management and feeding for native chicken.",
        location: "Lakewood, Zamboanga del Sur",
        facilitator: "Provincial Veterinarian",
        participatingIpos: ["Subanen River Dwellers"],
        participating_ipo_ids: [9],
        lat: 7.8467,
        lng: 123.1585,
        participantsMale: 18,
        participantsFemale: 12,
        expenses: [
            { id: 7, objectType: "MOOE", expenseParticular: "Training Expenses", uacsCode: "50202010-01", obligationMonth: "2024-07-20", disbursementMonth: "2024-08-10", amount: 28000 }
        ],
        component: "Production and Livelihood",
        fundingYear: 2024,
        fundType: "Insertion",
        tier: "Tier 1",
        operatingUnit: "RPMO 9",
        encodedBy: "Timuay Jose",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 8,
        uid: "TRN-2024-008",
        name: "Root Crops Value Addition",
        date: "2024-09-15",
        description: "Processing sweet potato into chips and flour.",
        location: "Abucay, Bataan",
        facilitator: "DOST Expert",
        participatingIpos: ["Aeta Magbukun Tribe"],
        participating_ipo_ids: [7],
        lat: 14.7196,
        lng: 120.5042,
        participantsMale: 5,
        participantsFemale: 25,
        expenses: [
            { id: 8, objectType: "MOOE", expenseParticular: "Training Expenses", uacsCode: "50202010-01", obligationMonth: "2024-08-30", disbursementMonth: "2024-09-20", amount: 32000 }
        ],
        component: "Marketing and Enterprise",
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 2",
        operatingUnit: "RPMO 3",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 9,
        uid: "TRN-2024-009",
        name: "Enterprise Development Workshop",
        date: "2023-10-25",
        description: "Business planning for handicraft souvenir shop.",
        location: "Malay, Aklan",
        facilitator: "DTI Aklan",
        participatingIpos: ["Ati Community of Boracay"],
        participating_ipo_ids: [10],
        lat: 11.9674,
        lng: 121.9248,
        participantsMale: 8,
        participantsFemale: 12,
        expenses: [
            { id: 9, objectType: "MOOE", expenseParticular: "Training Expenses", uacsCode: "50202010-01", obligationMonth: "2023-10-10", disbursementMonth: "2023-10-30", amount: 22000 }
        ],
        component: "Marketing and Enterprise",
        fundingYear: 2023,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO 6",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 10,
        uid: "TRN-2024-010",
        name: "Project Management Training for RPMO",
        date: "2024-01-15",
        description: "Training for regional staff on 4K program implementation.",
        location: "Quezon City (NCR)",
        facilitator: "NPMO Head",
        participatingIpos: [], // Staff training
        participating_ipo_ids: [],
        lat: 14.6460,
        lng: 121.0560,
        participantsMale: 10,
        participantsFemale: 15,
        expenses: [
            { id: 10, objectType: "MOOE", expenseParticular: "Training Expenses", uacsCode: "50202010-01", obligationMonth: "2024-01-05", disbursementMonth: "2024-01-20", amount: 100000, actualAmount: 95000, actualObligationDate: "2024-01-08", actualDisbursementDate: "2024-01-25" }
        ],
        component: "Program Management",
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "NPMO",
        encodedBy: "Admin User",
        actualDate: "2024-01-15",
        actualParticipantsMale: 10,
        actualParticipantsFemale: 15,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
];

// --- Sample Data: Other Activities (10 Entries) ---
export const sampleOtherActivities: OtherActivity[] = [
    {
        id: 1,
        uid: "ACT-2024-001",
        component: "Social Preparation",
        name: "Meetings",
        date: "2024-01-10",
        description: "Consultation meeting with IPO leaders regarding proposed projects.",
        location: "Brgy. Daraitan, Tanay, Rizal",
        participatingIpos: ["Samahan ng mga Katutubong Dumagat"],
        participating_ipo_ids: [1],
        participantsMale: 5,
        participantsFemale: 3,
        expenses: [
            { id: 1, objectType: "MOOE", expenseParticular: "Other MOOE", uacsCode: "50299990-99", obligationMonth: "2024-01-05", disbursementMonth: "2024-01-15", amount: 5000, actualAmount: 4800, actualObligationDate: "2024-01-07", actualDisbursementDate: "2024-01-18" }
        ],
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO 4A",
        encodedBy: "Juan Dela Cruz",
        actualDate: "2024-01-10",
        actualParticipantsMale: 5,
        actualParticipantsFemale: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 2,
        uid: "ACT-2024-002",
        component: "Social Preparation",
        name: "IPO Registration Drive (RSBSA, SEC, DOLE, CDA)",
        date: "2024-02-20",
        description: "Assisting IPO members in RSBSA registration.",
        location: "Prosperidad, Agusan del Sur",
        participatingIpos: ["Manobo Cultural Community Inc."],
        participating_ipo_ids: [4],
        participantsMale: 30,
        participantsFemale: 20,
        expenses: [
            { id: 2, objectType: "MOOE", expenseParticular: "Travelling Expenses", uacsCode: "50201010-00", obligationMonth: "2024-02-10", disbursementMonth: "2024-02-25", amount: 8000 }
        ],
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 2",
        operatingUnit: "RPMO 13",
        encodedBy: "Bae Aida",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 3,
        uid: "ACT-2024-003",
        component: "Program Management",
        name: "Sub-Project Monitoring",
        date: "2024-03-15",
        description: "Monitoring of Coffee Production project.",
        location: "Brgy. Daraitan, Tanay, Rizal",
        participatingIpos: ["Samahan ng mga Katutubong Dumagat"],
        participating_ipo_ids: [1],
        participantsMale: 2,
        participantsFemale: 1,
        expenses: [
            { id: 3, objectType: "MOOE", expenseParticular: "Travelling Expenses", uacsCode: "50201010-00", obligationMonth: "2024-03-01", disbursementMonth: "2024-03-20", amount: 3000 }
        ],
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO 4A",
        encodedBy: "Juan Dela Cruz",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 4,
        uid: "ACT-2024-004",
        component: "Marketing and Enterprise",
        name: "Market Linkaging",
        date: "2024-04-05",
        description: "Meeting with institutional buyers for Abaca.",
        location: "Cagayan de Oro City",
        participatingIpos: ["Higaonon Tribal Farmers Association"],
        participating_ipo_ids: [3],
        participantsMale: 3,
        participantsFemale: 2,
        expenses: [
            { id: 4, objectType: "MOOE", expenseParticular: "Representation Expenses", uacsCode: "50299030-00", obligationMonth: "2024-03-25", disbursementMonth: "2024-04-10", amount: 4000 }
        ],
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO 10",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 5,
        uid: "ACT-2024-005",
        component: "Social Preparation",
        name: "Community Needs Assessment",
        date: "2024-01-25",
        description: "Validation of community needs for proposal.",
        location: "Abucay, Bataan",
        participatingIpos: ["Aeta Magbukun Tribe"],
        participating_ipo_ids: [7],
        participantsMale: 10,
        participantsFemale: 15,
        expenses: [
            { id: 5, objectType: "MOOE", expenseParticular: "Other MOOE", uacsCode: "50299990-99", obligationMonth: "2024-01-15", disbursementMonth: "2024-01-30", amount: 6000 }
        ],
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 2",
        operatingUnit: "RPMO 3",
        encodedBy: "Kapitan Tubig",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 6,
        uid: "ACT-2024-006",
        component: "Program Management",
        name: "Performance and Budget Utilization Review (PBUR)",
        date: "2024-06-25",
        description: "Mid-year assessment of RPMO performance.",
        location: "Baguio City",
        participatingIpos: [],
        participating_ipo_ids: [],
        participantsMale: 15,
        participantsFemale: 20,
        expenses: [
            { id: 6, objectType: "MOOE", expenseParticular: "Representation Expenses", uacsCode: "50299030-00", obligationMonth: "2024-06-10", disbursementMonth: "2024-06-30", amount: 50000 }
        ],
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO CAR",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 7,
        uid: "ACT-2024-007",
        component: "Social Preparation",
        name: "Profiling",
        date: "2024-02-10",
        description: "Updating IPO member profiles.",
        location: "Lake Sebu, South Cotabato",
        participatingIpos: ["Tboli Weavers Association"],
        participating_ipo_ids: [5],
        participantsMale: 0,
        participantsFemale: 5,
        expenses: [
            { id: 7, objectType: "MOOE", expenseParticular: "Office Supplies Expenses", uacsCode: "50203010-01", obligationMonth: "2024-02-01", disbursementMonth: "2024-02-15", amount: 2000 }
        ],
        fundingYear: 2024,
        fundType: "Continuing",
        tier: "Tier 1",
        operatingUnit: "RPMO 12",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 8,
        uid: "ACT-2024-008",
        component: "Program Management",
        name: "Planning and BEDS Preparation",
        date: "2023-11-15",
        description: "Preparation of FY 2024 Plan.",
        location: "Iloilo City",
        participatingIpos: [],
        participating_ipo_ids: [],
        participantsMale: 5,
        participantsFemale: 5,
        expenses: [
            { id: 8, objectType: "MOOE", expenseParticular: "Other MOOE", uacsCode: "50299990-99", obligationMonth: "2023-11-01", disbursementMonth: "2023-11-20", amount: 15000 }
        ],
        fundingYear: 2023,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO 6",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 9,
        uid: "ACT-2024-009",
        component: "Social Preparation",
        name: "Review and Planning Workshop",
        date: "2024-05-20",
        description: "IPO level planning for next cropping season.",
        location: "La Trinidad, Benguet",
        participatingIpos: ["Igorot Organic Farmers"],
        participating_ipo_ids: [6],
        participantsMale: 15,
        participantsFemale: 15,
        expenses: [
            { id: 9, objectType: "MOOE", expenseParticular: "Other MOOE", uacsCode: "50299990-99", obligationMonth: "2024-05-05", disbursementMonth: "2024-05-25", amount: 10000 }
        ],
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO CAR",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 10,
        uid: "ACT-2024-010",
        component: "Marketing and Enterprise",
        name: "Trade and Promotional Activity",
        date: "2024-08-15",
        description: "Participation in Regional Agro-Trade Fair.",
        location: "Cagayan de Oro City",
        participatingIpos: ["Higaonon Tribal Council", "Manobo Tribal Association"],
        participating_ipo_ids: [6, 9], // Mock IDs
        participantsMale: 4,
        participantsFemale: 6,
        expenses: [
            { id: 10, objectType: "MOOE", expenseParticular: "Rent Expenses", uacsCode: "50299070-00", obligationMonth: "2024-07-30", disbursementMonth: "2024-08-10", amount: 25000 }
        ],
        fundingYear: 2024,
        fundType: "Current",
        tier: "Tier 1",
        operatingUnit: "RPMO 10",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
];

// --- Sample Data: Office Requirements (10 Entries) ---
export const sampleOfficeRequirements: OfficeRequirement[] = [
    {
        id: 1,
        uid: "OR-2024-001",
        operatingUnit: "RPMO 4A",
        uacsCode: "10605010-00",
        obligationDate: "2024-01-15",
        disbursementDate: "2024-02-01",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        equipment: "Laptop",
        specs: "Intel i5, 8GB RAM, 512GB SSD",
        purpose: "For Project Monitoring Officer",
        numberOfUnits: 2,
        pricePerUnit: 45000,
        encodedBy: "Juan Dela Cruz",
        actualDate: "2024-02-01",
        actualAmount: 90000,
        actualObligationDate: "2024-01-18",
        actualDisbursementDate: "2024-02-05",
        actualObligationAmount: 90000,
        actualDisbursementAmount: 90000,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 2,
        uid: "OR-2024-002",
        operatingUnit: "RPMO 10",
        uacsCode: "10605010-00",
        obligationDate: "2024-02-15",
        disbursementDate: "2024-03-01",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        equipment: "Printer",
        specs: "3-in-1 Ink Tank",
        purpose: "Office documentation",
        numberOfUnits: 1,
        pricePerUnit: 12000,
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 3,
        uid: "OR-2024-003",
        operatingUnit: "RPMO 13",
        uacsCode: "50203010-01",
        obligationDate: "2024-01-10",
        disbursementDate: "2024-01-25",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 2",
        equipment: "External Hard Drive",
        specs: "2TB USB 3.0",
        purpose: "Data backup",
        numberOfUnits: 3,
        pricePerUnit: 4000,
        encodedBy: "Bae Aida",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 4,
        uid: "OR-2024-004",
        operatingUnit: "RPMO CAR",
        uacsCode: "10605010-00",
        obligationDate: "2024-03-20",
        disbursementDate: "2024-04-05",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        equipment: "Projector",
        specs: "LCD 3600 Lumens",
        purpose: "Trainings and workshops",
        numberOfUnits: 1,
        pricePerUnit: 25000,
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 5,
        uid: "OR-2024-005",
        operatingUnit: "RPMO 9",
        uacsCode: "50203010-01",
        obligationDate: "2024-01-05",
        disbursementDate: "2024-01-20",
        fundType: "Insertion",
        fundYear: 2024,
        tier: "Tier 1",
        equipment: "Office Table",
        specs: "120x60cm wood",
        purpose: "Staff workstation",
        numberOfUnits: 2,
        pricePerUnit: 5000,
        encodedBy: "Timuay Jose",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 6,
        uid: "OR-2024-006",
        operatingUnit: "RPMO 12",
        uacsCode: "50203010-01",
        obligationDate: "2024-02-28",
        disbursementDate: "2024-03-15",
        fundType: "Continuing",
        fundYear: 2024,
        tier: "Tier 1",
        equipment: "Office Chair",
        specs: "Ergonomic mesh",
        purpose: "Staff workstation",
        numberOfUnits: 2,
        pricePerUnit: 3500,
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 7,
        uid: "OR-2024-007",
        operatingUnit: "RPMO 3",
        uacsCode: "10605010-00",
        obligationDate: "2024-04-15",
        disbursementDate: "2024-04-30",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        equipment: "Air Conditioner",
        specs: "2.0 HP Split Type",
        purpose: "Office cooling",
        numberOfUnits: 1,
        pricePerUnit: 40000,
        encodedBy: "Kapitan Tubig",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 8,
        uid: "OR-2024-008",
        operatingUnit: "NPMO",
        uacsCode: "10605010-00",
        obligationDate: "2024-01-20",
        disbursementDate: "2024-02-10",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        equipment: "Desktop Computer",
        specs: "i7, 16GB RAM, Dedicated GPU",
        purpose: "GIS Mapping",
        numberOfUnits: 1,
        pricePerUnit: 70000,
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 9,
        uid: "OR-2024-009",
        operatingUnit: "RPMO 6",
        uacsCode: "50203010-01",
        obligationDate: "2023-12-01",
        disbursementDate: "2023-12-15",
        fundType: "Current",
        fundYear: 2023,
        tier: "Tier 1",
        equipment: "Filing Cabinet",
        specs: "4-drawer steel",
        purpose: "Document storage",
        numberOfUnits: 4,
        pricePerUnit: 8000,
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 10,
        uid: "OR-2024-010",
        operatingUnit: "RPMO 13",
        uacsCode: "10605010-00",
        obligationDate: "2024-07-15",
        disbursementDate: "2024-07-30",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        equipment: "Camera",
        specs: "DSLR with kit lens",
        purpose: "For documentation",
        numberOfUnits: 1,
        pricePerUnit: 35000,
        encodedBy: "Bae Aida",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
];

// --- Sample Data: Staffing Requirements (10 Entries) ---
export const sampleStaffingRequirements: StaffingRequirement[] = [
    {
        id: 1,
        uid: "SR-2024-001",
        operatingUnit: "RPMO 4A",
        uacsCode: "50101010-01",
        obligationDate: "2024-01-01",
        disbursementDate: "2024-01-31",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        personnelPosition: "Project Development Officer II",
        status: "Contractual",
        salaryGrade: 15,
        annualSalary: 420000,
        personnelType: "Technical",
        encodedBy: "Juan Dela Cruz",
        actualDate: "2024-01-31",
        actualAmount: 35000, 
        actualObligationDate: "2024-01-05",
        actualDisbursementDate: "2024-01-31",
        actualObligationAmount: 35000,
        actualDisbursementAmount: 35000,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 2,
        uid: "SR-2024-002",
        operatingUnit: "RPMO 10",
        uacsCode: "50101010-01",
        obligationDate: "2024-01-01",
        disbursementDate: "2024-01-31",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        personnelPosition: "Project Development Officer I",
        status: "Contractual",
        salaryGrade: 11,
        annualSalary: 324000,
        personnelType: "Technical",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 3,
        uid: "SR-2024-003",
        operatingUnit: "RPMO 13",
        uacsCode: "50101010-01",
        obligationDate: "2024-01-01",
        disbursementDate: "2024-01-31",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 2",
        personnelPosition: "Admin Assistant II",
        status: "Contractual",
        salaryGrade: 8,
        annualSalary: 230000,
        personnelType: "Administrative",
        encodedBy: "Bae Aida",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 4,
        uid: "SR-2024-004",
        operatingUnit: "RPMO CAR",
        uacsCode: "50101010-01",
        obligationDate: "2024-01-01",
        disbursementDate: "2024-01-31",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        personnelPosition: "Community Development Officer I",
        status: "Contractual",
        salaryGrade: 11,
        annualSalary: 324000,
        personnelType: "Technical",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 5,
        uid: "SR-2024-005",
        operatingUnit: "RPMO 9",
        uacsCode: "50101010-01",
        obligationDate: "2024-01-01",
        disbursementDate: "2024-01-31",
        fundType: "Insertion",
        fundYear: 2024,
        tier: "Tier 1",
        personnelPosition: "Driver",
        status: "Job Order",
        salaryGrade: 4,
        annualSalary: 150000,
        personnelType: "Support",
        encodedBy: "Timuay Jose",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 6,
        uid: "SR-2024-006",
        operatingUnit: "RPMO 12",
        uacsCode: "50101010-01",
        obligationDate: "2024-01-01",
        disbursementDate: "2024-01-31",
        fundType: "Continuing",
        fundYear: 2024,
        tier: "Tier 1",
        personnelPosition: "Project Evaluation Officer",
        status: "Contractual",
        salaryGrade: 11,
        annualSalary: 324000,
        personnelType: "Technical",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 7,
        uid: "SR-2024-007",
        operatingUnit: "RPMO 3",
        uacsCode: "50101010-01",
        obligationDate: "2024-01-01",
        disbursementDate: "2024-01-31",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        personnelPosition: "Admin Aide",
        status: "Job Order",
        salaryGrade: 3,
        annualSalary: 140000,
        personnelType: "Support",
        encodedBy: "Kapitan Tubig",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 8,
        uid: "SR-2024-008",
        operatingUnit: "NPMO",
        uacsCode: "50101010-01",
        obligationDate: "2024-01-01",
        disbursementDate: "2024-01-31",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        personnelPosition: "Senior Project Development Officer",
        status: "Contractual",
        salaryGrade: 18,
        annualSalary: 540000,
        personnelType: "Technical",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 9,
        uid: "SR-2024-009",
        operatingUnit: "RPMO 6",
        uacsCode: "50101010-01",
        obligationDate: "2023-01-01",
        disbursementDate: "2023-01-31",
        fundType: "Current",
        fundYear: 2023,
        tier: "Tier 1",
        personnelPosition: "Project Development Officer II",
        status: "Contractual",
        salaryGrade: 15,
        annualSalary: 420000,
        personnelType: "Technical",
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 10,
        uid: "SR-2024-010",
        operatingUnit: "RPMO 13",
        uacsCode: "50101010-01",
        obligationDate: "2024-01-01",
        disbursementDate: "2024-01-31",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        personnelPosition: "Encoder",
        status: "Job Order",
        salaryGrade: 6,
        annualSalary: 180000,
        personnelType: "Support",
        encodedBy: "Bae Aida",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
];

// --- Sample Data: Other Program Expenses (10 Entries) ---
export const sampleOtherProgramExpenses: OtherProgramExpense[] = [
    {
        id: 1,
        uid: "OE-2024-001",
        operatingUnit: "RPMO 4A",
        uacsCode: "50203010-01",
        obligationDate: "2024-02-10",
        disbursementDate: "2024-02-25",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        particulars: "Office Supplies for Q1",
        amount: 15000,
        encodedBy: "Juan Dela Cruz",
        actualDate: "2024-02-25",
        actualAmount: 14500,
        actualObligationDate: "2024-02-12",
        actualDisbursementDate: "2024-02-27",
        actualObligationAmount: 15000,
        actualDisbursementAmount: 14500,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 2,
        uid: "OE-2024-002",
        operatingUnit: "RPMO 10",
        uacsCode: "50204020-00",
        obligationDate: "2024-01-30",
        disbursementDate: "2024-02-15",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        particulars: "Electricity Bill (Jan)",
        amount: 8000,
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 3,
        uid: "OE-2024-003",
        operatingUnit: "RPMO 13",
        uacsCode: "50204010-00",
        obligationDate: "2024-01-30",
        disbursementDate: "2024-02-15",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 2",
        particulars: "Water Bill (Jan)",
        amount: 1500,
        encodedBy: "Bae Aida",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 4,
        uid: "OE-2024-004",
        operatingUnit: "RPMO CAR",
        uacsCode: "50299070-00",
        obligationDate: "2024-01-05",
        disbursementDate: "2024-01-10",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        particulars: "Office Rent (Jan-Mar)",
        amount: 45000,
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 5,
        uid: "OE-2024-005",
        operatingUnit: "RPMO 9",
        uacsCode: "50213050-00",
        obligationDate: "2024-03-10",
        disbursementDate: "2024-03-25",
        fundType: "Insertion",
        fundYear: 2024,
        tier: "Tier 1",
        particulars: "Vehicle Repair",
        amount: 12000,
        encodedBy: "Timuay Jose",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 6,
        uid: "OE-2024-006",
        operatingUnit: "RPMO 12",
        uacsCode: "50299990-99",
        obligationDate: "2024-02-15",
        disbursementDate: "2024-02-28",
        fundType: "Continuing",
        fundYear: 2024,
        tier: "Tier 1",
        particulars: "Internet Subscription (Jan)",
        amount: 3000,
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 7,
        uid: "OE-2024-007",
        operatingUnit: "RPMO 3",
        uacsCode: "50203010-01",
        obligationDate: "2024-02-01",
        disbursementDate: "2024-02-15",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        particulars: "Janitorial Supplies",
        amount: 5000,
        encodedBy: "Kapitan Tubig",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 8,
        uid: "OE-2024-008",
        operatingUnit: "NPMO",
        uacsCode: "50211010-00",
        obligationDate: "2024-03-01",
        disbursementDate: "2024-03-15",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        particulars: "Legal Consultation Fee",
        amount: 25000,
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 9,
        uid: "OE-2024-009",
        operatingUnit: "RPMO 6",
        uacsCode: "50299030-00",
        obligationDate: "2023-12-10",
        disbursementDate: "2023-12-20",
        fundType: "Current",
        fundYear: 2023,
        tier: "Tier 1",
        particulars: "Year-end Assessment Meals",
        amount: 10000,
        encodedBy: "Admin User",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 10,
        uid: "OE-2024-010",
        operatingUnit: "RPMO 13",
        uacsCode: "50299990-99",
        obligationDate: "2024-02-01",
        disbursementDate: "2024-02-15",
        fundType: "Current",
        fundYear: 2024,
        tier: "Tier 1",
        particulars: "Courier Services",
        amount: 2000,
        encodedBy: "Bae Aida",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
];
