
// Author: AI
// OS support: Any
import { IPO } from './constants';

// --- Sample Data: IPOs (10 Entries) ---
export const sampleIPOs: IPO[] = [
    {
        id: 1,
        name: "Samahan ng mga Katutubong Dumagat",
        location: "Brgy. Daraitan, Tanay, Rizal",
        region: "Region IV-A (CALABARZON)",
        indigenousCulturalCommunity: "Dumagat",
        ancestralDomainNo: "R4A-RIZ-TAN-001",
        registeringBody: "SEC",
        isWomenLed: false,
        isWithinGida: true,
        isWithinElcac: false,
        isWithScad: true,
        contactPerson: "Juan dela Cruz",
        contactNumber: "09171234567",
        registrationDate: "2020-05-15",
        commodities: [{ type: "Crop Commodity", particular: "Coffee Seedlings", value: 50, isScad: true }],
        levelOfDevelopment: 3,
        lat: 14.6127,
        lng: 121.3632,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 2,
        name: "Dumagat-Remontado of General Nakar",
        location: "General Nakar, Quezon",
        region: "Region IV-A (CALABARZON)",
        indigenousCulturalCommunity: "Dumagat-Remontado",
        ancestralDomainNo: "R4A-QUE-GEN-010",
        registeringBody: "NCIP",
        isWomenLed: true,
        isWithinGida: true,
        isWithinElcac: true,
        isWithScad: true,
        contactPerson: "Kakay Tolits",
        contactNumber: "09151112222",
        registrationDate: "2018-05-25",
        commodities: [{ type: "Crop Commodity", particular: "Coconut", value: 200, isScad: true }],
        levelOfDevelopment: 3,
        lat: 14.7648,
        lng: 121.6366,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 3,
        name: "Higaonon Tribal Farmers Association",
        location: "Malaybalay City, Bukidnon",
        region: "Region X (Northern Mindanao)",
        indigenousCulturalCommunity: "Higaonon",
        ancestralDomainNo: "R10-BUK-MAL-003",
        registeringBody: "DOLE",
        isWomenLed: false,
        isWithinGida: true,
        isWithinElcac: false,
        isWithScad: true,
        contactPerson: "Datu Mantukay",
        contactNumber: "09181234567",
        registrationDate: "2019-02-10",
        commodities: [{ type: "Crop Commodity", particular: "Abaca Corms", value: 15, isScad: true }],
        levelOfDevelopment: 2,
        lat: 8.1574,
        lng: 125.1277,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 4,
        name: "Manobo Cultural Community Inc.",
        location: "Prosperidad, Agusan del Sur",
        region: "Region XIII (Caraga)",
        indigenousCulturalCommunity: "Manobo",
        ancestralDomainNo: "R13-AGS-PRO-004",
        registeringBody: "SEC",
        isWomenLed: true,
        isWithinGida: true,
        isWithinElcac: true,
        isWithScad: false,
        contactPerson: "Bae Aida",
        contactNumber: "09201234567",
        registrationDate: "2021-08-15",
        commodities: [{ type: "Crop Commodity", particular: "Cacao", value: 10, isScad: false }],
        levelOfDevelopment: 2,
        lat: 8.5990,
        lng: 125.9220,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 5,
        name: "Tboli Weavers Association",
        location: "Lake Sebu, South Cotabato",
        region: "Region XII (SOCCSKSARGEN)",
        indigenousCulturalCommunity: "Tboli",
        ancestralDomainNo: "R12-SOC-LAK-005",
        registeringBody: "CDA",
        isWomenLed: true,
        isWithinGida: false,
        isWithinElcac: false,
        isWithScad: true,
        contactPerson: "Ye Lang Dulay",
        contactNumber: "09191234567",
        registrationDate: "2017-11-20",
        commodities: [{ type: "Equipment", particular: "Weaving Loom", value: 20, isScad: true }],
        levelOfDevelopment: 4,
        lat: 6.2239,
        lng: 124.7032,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 6,
        name: "Igorot Organic Farmers",
        location: "La Trinidad, Benguet",
        region: "Cordillera Administrative Region (CAR)",
        indigenousCulturalCommunity: "Igorot",
        ancestralDomainNo: "CAR-BEN-LAT-006",
        registeringBody: "DOLE",
        isWomenLed: false,
        isWithinGida: false,
        isWithinElcac: false,
        isWithScad: true,
        contactPerson: "Manong Ben",
        contactNumber: "09179998888",
        registrationDate: "2016-03-12",
        commodities: [{ type: "Crop Commodity", particular: "Vegetable Seeds", value: 100, isScad: true }],
        levelOfDevelopment: 5,
        lat: 16.4568,
        lng: 120.5896,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 7,
        name: "Aeta Magbukun Tribe",
        location: "Abucay, Bataan",
        region: "Region III (Central Luzon)",
        indigenousCulturalCommunity: "Aeta",
        ancestralDomainNo: "R3-BAT-ABU-007",
        registeringBody: "NCIP",
        isWomenLed: false,
        isWithinGida: true,
        isWithinElcac: true,
        isWithScad: false,
        contactPerson: "Kapitan Tubig",
        contactNumber: "09165554444",
        registrationDate: "2022-01-10",
        commodities: [{ type: "Crop Commodity", particular: "Sweet Potato", value: 5, isScad: false }],
        levelOfDevelopment: 1,
        lat: 14.7196,
        lng: 120.5042,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 8,
        name: "Mangyan Hanunuo Heritage",
        location: "Mansalay, Oriental Mindoro",
        region: "MIMAROPA Region",
        indigenousCulturalCommunity: "Mangyan",
        ancestralDomainNo: "R4B-ORM-MAN-008",
        registeringBody: "SEC",
        isWomenLed: true,
        isWithinGida: true,
        isWithinElcac: false,
        isWithScad: true,
        contactPerson: "Nanay Lita",
        contactNumber: "09187776666",
        registrationDate: "2019-09-09",
        commodities: [{ type: "Crop Commodity", particular: "Banana", value: 50, isScad: true }],
        levelOfDevelopment: 2,
        lat: 12.5463,
        lng: 121.4392,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 9,
        name: "Subanen River Dwellers",
        location: "Lakewood, Zamboanga del Sur",
        region: "Region IX (Zamboanga Peninsula)",
        indigenousCulturalCommunity: "Subanen",
        ancestralDomainNo: "R9-ZDS-LAK-009",
        registeringBody: "CDA",
        isWomenLed: false,
        isWithinGida: true,
        isWithinElcac: true,
        isWithScad: true,
        contactPerson: "Timuay Jose",
        contactNumber: "09213332222",
        registrationDate: "2020-12-01",
        commodities: [{ type: "Livestock", particular: "Chicken", value: 500, isScad: true }],
        levelOfDevelopment: 3,
        lat: 7.8467,
        lng: 123.1585,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 10,
        name: "Ati Community of Boracay",
        location: "Malay, Aklan",
        region: "Region VI (Western Visayas)",
        indigenousCulturalCommunity: "Ati",
        ancestralDomainNo: "R6-AKL-MAL-010",
        registeringBody: "NCIP",
        isWomenLed: true,
        isWithinGida: false,
        isWithinElcac: false,
        isWithScad: true,
        contactPerson: "Sister Delsa",
        contactNumber: "09171110000",
        registrationDate: "2015-06-15",
        commodities: [{ type: "Other", particular: "Handicrafts", value: 100, isScad: true }],
        levelOfDevelopment: 4,
        lat: 11.9674,
        lng: 121.9248,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
];
