import ExcelJS from 'exceljs';
import {
    GAD_HGDG_ATTRIBUTION_RATE,
    GAD_HGDG_MAX_SCORE,
    GAD_HGDG_SCORE,
} from './gadAttribution.ts';

export interface GadAttributionExportRow {
    ou: string;
    state: string;
    pimmeScore: number | null;
    allocation: number;
    obligation: number;
    attributableAllocation: number;
    attributableObligation: number | null;
}

export interface GadAttributionExportInput {
    year: number;
    ouScope: string;
    rows: GadAttributionExportRow[];
    generatedAt?: Date;
}

const MONEY_FORMAT = '[$₱]#,##0.00;[Red]-[$₱]#,##0.00;[$₱]-';
const THIN_BORDER: Partial<ExcelJS.Borders> = {
    top: { style: 'thin', color: { argb: 'FF000000' } },
    left: { style: 'thin', color: { argb: 'FF000000' } },
    bottom: { style: 'thin', color: { argb: 'FF000000' } },
    right: { style: 'thin', color: { argb: 'FF000000' } },
};

const sanitizeFileToken = (value: string) => value.trim()
    .replace(/[^a-zA-Z0-9_-]+/g, '_')
    .replace(/^_+|_+$/g, '') || 'All_OUs';

const formatDateToken = (date: Date) => {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
};

const formatLongDate = (date: Date) => new Intl.DateTimeFormat('en-PH', {
    month: 'long', day: 'numeric', year: 'numeric',
}).format(date);

const styleRange = (worksheet: ExcelJS.Worksheet, range: string, style: Partial<ExcelJS.Style>) => {
    const [start, end] = range.split(':');
    const startCell = worksheet.getCell(start);
    const endCell = worksheet.getCell(end || start);
    for (let row = startCell.row; row <= endCell.row; row += 1) {
        for (let column = startCell.col; column <= endCell.col; column += 1) {
            const cell = worksheet.getCell(row, column);
            Object.assign(cell, style);
        }
    }
};

export const buildGadAttributionWorkbook = ({
    year,
    ouScope,
    rows,
    generatedAt = new Date(),
}: GadAttributionExportInput) => {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = '4K Information System';
    workbook.created = generatedAt;
    workbook.modified = generatedAt;
    workbook.calcProperties.fullCalcOnLoad = true;

    const worksheet = workbook.addWorksheet(String(year).slice(0, 31), {
        pageSetup: {
            orientation: 'landscape',
            fitToPage: true,
            fitToWidth: 1,
            fitToHeight: 0,
            paperSize: 9,
        },
        properties: { defaultRowHeight: 18 },
    });
    worksheet.views = [{ state: 'frozen', ySplit: 8, xSplit: 2 }];
    worksheet.pageSetup.margins = {
        left: 0.25, right: 0.25, top: 0.4, bottom: 0.4, header: 0.2, footer: 0.2,
    };
    worksheet.pageSetup.printArea = `C1:I${Math.max(10, rows.length + 9)}`;

    worksheet.getColumn('A').width = 1;
    worksheet.getColumn('B').width = 1;
    worksheet.getColumn('C').width = 14;
    worksheet.getColumn('D').width = 21;
    worksheet.getColumn('E').width = 22;
    worksheet.getColumn('F').width = 25;
    worksheet.getColumn('G').width = 16;
    worksheet.getColumn('H').width = 28;
    worksheet.getColumn('I').width = 38;
    worksheet.getColumn('J').width = 16;

    worksheet.getCell('J1').value = 'Important Note:';
    worksheet.getCell('J1').font = { name: 'Arial', size: 10, bold: true };
    worksheet.getCell('J2').value = '- Generated by 4KIS. Derived cells contain formulas.';
    worksheet.getCell('J4').value = `Fund Year ${year} · ${ouScope}`;
    worksheet.getCell('J4').font = { name: 'Arial', size: 10, italic: true };

    worksheet.mergeCells('C7:F7');
    worksheet.mergeCells('G7:I7');
    worksheet.getCell('C7').value = `DA-4K PROGRAM BUDGET FOR CY ${year}`;
    worksheet.getCell('G7').value = `ACTUAL EXPENDITURES FOR CY ${year} (as of ${formatLongDate(generatedAt)})`;
    worksheet.getRow(7).height = 34;

    ['C7', 'G7'].forEach((address, index) => {
        const cell = worksheet.getCell(address);
        cell.fill = {
            type: 'pattern', pattern: 'solid',
            fgColor: { argb: index === 0 ? 'FFB4A7D6' : 'FFD5A6BD' },
        };
        cell.font = { name: 'Arial', size: 12, bold: true };
        cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
        cell.border = THIN_BORDER;
    });

    const headers = [
        'Region / OU',
        `FY ${year} Budget`,
        'Computation',
        `Attributable Amount in the GPB ${year}`,
        'PIMME Result',
        'Total Expenses (Obligated)',
        'Attributed Amount',
    ];
    headers.forEach((header, index) => {
        const cell = worksheet.getCell(8, index + 3);
        cell.value = header;
        cell.font = { name: 'Arial', size: 11, bold: true };
        cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
        cell.border = THIN_BORDER;
    });
    worksheet.getRow(8).height = 48;

    const firstDataRow = 9;
    const dataRows = rows.length ? rows : [{
        ou: 'No OUs match the current dashboard filters',
        state: 'No Data',
        pimmeScore: null,
        allocation: 0,
        obligation: 0,
        attributableAllocation: 0,
        attributableObligation: null,
    }];
    const lastDataRow = firstDataRow + dataRows.length - 1;
    const totalRow = lastDataRow + 1;

    worksheet.mergeCells(`E${firstDataRow}:E${totalRow}`);
    const computationCell = worksheet.getCell(`E${firstDataRow}`);
    computationCell.value = [
        `HGDG Score: ${GAD_HGDG_SCORE.toFixed(2)}`,
        '',
        `${GAD_HGDG_SCORE.toFixed(2)}/${GAD_HGDG_MAX_SCORE} = ${GAD_HGDG_ATTRIBUTION_RATE.toFixed(4)}`,
        '',
        `${(GAD_HGDG_ATTRIBUTION_RATE * 100).toFixed(2)}% x BUDGET`,
    ].join('\n');
    computationCell.font = { name: 'Arial', size: 11 };
    computationCell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };

    dataRows.forEach((row, index) => {
        const rowNumber = firstDataRow + index;
        const excelRow = worksheet.getRow(rowNumber);
        excelRow.height = 23;
        worksheet.getCell(`C${rowNumber}`).value = row.ou;
        worksheet.getCell(`D${rowNumber}`).value = row.allocation;
        worksheet.getCell(`F${rowNumber}`).value = {
            formula: `(${GAD_HGDG_SCORE}/${GAD_HGDG_MAX_SCORE})*D${rowNumber}`,
            result: row.attributableAllocation,
        };
        worksheet.getCell(`G${rowNumber}`).value = row.pimmeScore ?? null;
        worksheet.getCell(`H${rowNumber}`).value = row.obligation;
        worksheet.getCell(`I${rowNumber}`).value = row.pimmeScore === null
            ? null
            : {
                formula: `(G${rowNumber}/${GAD_HGDG_MAX_SCORE})*H${rowNumber}`,
                result: row.attributableObligation ?? 0,
            };
        if (row.pimmeScore === null && rows.length) worksheet.getCell(`G${rowNumber}`).note = row.state;

        ['D', 'F', 'H', 'I'].forEach(column => { worksheet.getCell(`${column}${rowNumber}`).numFmt = MONEY_FORMAT; });
        worksheet.getCell(`G${rowNumber}`).numFmt = '0.00';
        styleRange(worksheet, `C${rowNumber}:I${rowNumber}`, {
            font: { name: 'Arial', size: 11 },
            alignment: { horizontal: 'center', vertical: 'middle' },
            border: THIN_BORDER,
        });
    });

    worksheet.getCell(`C${totalRow}`).value = 'TOTAL';
    worksheet.getCell(`D${totalRow}`).value = {
        formula: `SUM(D${firstDataRow}:D${lastDataRow})`,
        result: rows.reduce((sum, row) => sum + row.allocation, 0),
    };
    worksheet.getCell(`F${totalRow}`).value = {
        formula: `SUM(F${firstDataRow}:F${lastDataRow})`,
        result: rows.reduce((sum, row) => sum + row.attributableAllocation, 0),
    };
    worksheet.getCell(`G${totalRow}`).value = {
        formula: `SUM(G${firstDataRow}:G${lastDataRow})`,
        result: rows.reduce((sum, row) => sum + (row.pimmeScore ?? 0), 0),
    };
    worksheet.getCell(`H${totalRow}`).value = {
        formula: `SUM(H${firstDataRow}:H${lastDataRow})`,
        result: rows.reduce((sum, row) => sum + row.obligation, 0),
    };
    worksheet.getCell(`I${totalRow}`).value = {
        formula: `SUM(I${firstDataRow}:I${lastDataRow})`,
        result: rows.reduce((sum, row) => sum + (row.attributableObligation ?? 0), 0),
    };
    worksheet.getRow(totalRow).height = 23;
    styleRange(worksheet, `C${totalRow}:I${totalRow}`, {
        font: { name: 'Arial', size: 11, bold: true },
        alignment: { horizontal: 'center', vertical: 'middle' },
        border: THIN_BORDER,
    });
    ['D', 'F', 'H', 'I'].forEach(column => { worksheet.getCell(`${column}${totalRow}`).numFmt = MONEY_FORMAT; });
    worksheet.getCell(`G${totalRow}`).numFmt = '0.00';

    return workbook;
};

export const downloadGadAttributionWorkbook = async (input: GadAttributionExportInput) => {
    const generatedAt = input.generatedAt ?? new Date();
    const workbook = buildGadAttributionWorkbook({ ...input, generatedAt });
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], {
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `GAD_Attribution_Calculator_FY${input.year}_${sanitizeFileToken(input.ouScope)}_${formatDateToken(generatedAt)}.xlsx`;
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    URL.revokeObjectURL(url);
};
