-- Introduce the global Fund Source reference and additive UID links for Subprojects.
-- Existing Fund Source text is retained; only the new UID column is backfilled.

create sequence if not exists public.ref_fund_source_uid_seq;

create table if not exists public.ref_fund_sources (
  id bigint generated by default as identity primary key,
  uid text not null unique,
  label text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  constraint ref_fund_sources_label_not_blank check (nullif(btrim(label), '') is not null)
);

alter table public.ref_fund_sources
  alter column uid drop default;

drop trigger if exists ref_fund_sources_assign_uid on public.ref_fund_sources;

create unique index if not exists ref_fund_sources_active_label_uidx
  on public.ref_fund_sources (lower(btrim(label)))
  where is_active;

insert into public.ref_fund_sources (uid, label, is_active, sort_order)
values
  ('FS-000001', '4K Fund', true, 1),
  ('FS-000002', 'High Value Crops', true, 2),
  ('FS-000003', 'Corn', true, 3),
  ('FS-000004', 'Rice', true, 4),
  ('FS-000005', 'Organic', true, 5),
  ('FS-000006', 'Livestock', true, 6)
on conflict (uid) do nothing;

select setval(
  'public.ref_fund_source_uid_seq',
  greatest(
    6,
    coalesce((select max(substring(uid from '^FS-([0-9]+)$')::bigint) from public.ref_fund_sources), 0),
    (select last_value from public.ref_fund_source_uid_seq)
  ),
  true
);

create or replace function public.assign_fund_source_uid()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.uid is not null then
    raise exception 'Fund Source UID is database-generated and cannot be supplied.';
  end if;

  new.uid := 'FS-' || lpad(nextval('public.ref_fund_source_uid_seq')::text, 6, '0');
  return new;
end;
$$;

create trigger ref_fund_sources_assign_uid
before insert on public.ref_fund_sources
for each row execute function public.assign_fund_source_uid();

create or replace function public.guard_fund_source_reference_update()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.uid is distinct from old.uid then
    raise exception 'Fund Source UID is immutable.';
  end if;
  new.updated_at := now();
  new.updated_by := auth.uid();
  return new;
end;
$$;

drop trigger if exists ref_fund_sources_guard_update on public.ref_fund_sources;
create trigger ref_fund_sources_guard_update
before update on public.ref_fund_sources
for each row execute function public.guard_fund_source_reference_update();

alter table public.subprojects
  add column if not exists "fundSourceUid" text;

alter table public.subprojects
  drop constraint if exists subprojects_fund_source_uid_fkey;

alter table public.subprojects
  add constraint subprojects_fund_source_uid_fkey
  foreign key ("fundSourceUid")
  references public.ref_fund_sources(uid)
  on update restrict
  on delete restrict;

create index if not exists subprojects_fund_source_uid_idx
  on public.subprojects ("fundSourceUid");

alter table public.subprojects
  drop constraint if exists subprojects_fund_source_check;

update public.subprojects as subproject
set "fundSourceUid" = reference.uid
from public.ref_fund_sources as reference
where subproject."fundSourceUid" is null
  and nullif(btrim(coalesce(subproject."fundSource", '')), '') is not null
  and lower(btrim(subproject."fundSource")) = lower(btrim(reference.label));

create or replace function public.can_edit_fund_source_references()
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  actor public.users%rowtype;
  role_can_edit boolean;
  override_value jsonb;
begin
  select * into actor
  from public.users
  where auth_id = auth.uid()
  limit 1;

  if actor.id is null then
    return false;
  end if;

  if actor.role in ('Super Admin', 'Administrator') then
    return true;
  end if;

  if actor.role = 'Guest' then
    return false;
  end if;

  override_value := actor.permissions_override -> 'References' -> 'can_edit';
  if jsonb_typeof(override_value) = 'boolean' then
    return (override_value #>> '{}')::boolean;
  end if;

  select rc.can_edit into role_can_edit
  from public.roles_config as rc
  where rc.role = actor.role
    and rc.module = 'References'
  limit 1;

  return coalesce(role_can_edit, false);
end;
$$;

alter table public.ref_fund_sources enable row level security;

drop policy if exists ref_fund_sources_view_policy on public.ref_fund_sources;
create policy ref_fund_sources_view_policy on public.ref_fund_sources
for select to authenticated
using (true);

drop policy if exists ref_fund_sources_insert_policy on public.ref_fund_sources;
create policy ref_fund_sources_insert_policy on public.ref_fund_sources
for insert to authenticated
with check (public.can_edit_fund_source_references());

drop policy if exists ref_fund_sources_update_policy on public.ref_fund_sources;
create policy ref_fund_sources_update_policy on public.ref_fund_sources
for update to authenticated
using (public.can_edit_fund_source_references())
with check (public.can_edit_fund_source_references());

revoke delete on public.ref_fund_sources from authenticated;
grant select, insert, update on public.ref_fund_sources to authenticated;
grant usage, select on sequence public.ref_fund_sources_id_seq to authenticated;
grant usage, select on sequence public.ref_fund_source_uid_seq to authenticated;

comment on column public.subprojects."fundSourceUid" is
  'Canonical Fund Source relationship. Legacy fundSource text remains for compatibility.';
